/**
 * locationPrompt.js — Resolve location key to full prompt description
 * Keys match CLAUDE.md LOCATION_DATA. Unknown keys returned as-is.
 */

const LOCATION_DATA = {
  bali_heaven:    'Pura Lempuyang Gates of Heaven Bali, iconic split gate Candi Bentar framing Mount Agung, mystical reflection pool below',
  bali_ubud:      'Tegallalang Rice Terrace Ubud Bali, lush terraced emerald green rice paddies cascading down the hillside, swaying palm trees',
  bali_ulun:      'Pura Ulun Danu Beratan Bedugul Bali, floating temple on misty crater lake, sacred multi-tiered pagoda, mountains surrounding',
  bali_beach:     'Melasti Beach Ungasan Bali, dramatic white limestone cliffs, pristine turquoise water, hidden cove',
  bali_cliff:     'Uluwatu Cliff Edge Bali, dramatic limestone cliff over crashing Indian Ocean waves, sunset ceremony',
  bali_jungle:    'Ubud Jungle and Hidden Waterfall Bali, lush tropical jungle, ancient banyan trees, dramatic hidden waterfall',
  labuan_bajo:    'Padar Island Labuan Bajo NTT, dramatic twin-peaked island, sweeping bay views, dry savanna grass, multiple colored bays',
  raja_ampat:     'Wayag Island Raja Ampat Papua Barat, limestone karst rising from the clearest turquoise lagoon in the world',
  yogya:          'Borobudur Temple Magelang Java, 9th century Buddhist temple, stupas at sunrise, Mount Merapi backdrop',
  prambanan:      'Prambanan Temple Yogyakarta, magnificent Hindu temple compound, soaring stone towers, intricate carvings',
  lombok:         'Pink Beach East Lombok, unique blush-pink sand, crystal clear turquoise Lombok Strait',
  nusa_penida:    'Kelingking Beach Nusa Penida, T-Rex shaped cliff promontory, vivid turquoise Indian Ocean below',
  jakarta_luxury: 'Luxury Hotel Rooftop Jakarta, panoramic Jakarta skyline, glittering city lights, infinity pool',
  kyoto_inari:    'Fushimi Inari Shrine Kyoto Japan, thousands of vermillion torii gates creating glowing red-orange tunnel through sacred mountain forest',
  kyoto_bambu:    'Arashiyama Bamboo Grove Kyoto Japan, towering bamboo stalks creating cathedral-like canopy, filtered morning light',
  sakura_park:    'Shinjuku Gyoen Tokyo Japan, hundreds of sakura cherry blossom trees in full bloom, pink petals falling like snow',
  fuji_lake:      'Lake Kawaguchiko Mount Fuji Japan, iconic snow-capped Mt. Fuji perfectly reflected in still lake, sunrise mist',
  seoul_studio:   'Seoul Urban Street Gangnam South Korea, modern urban Korean street, neon signs, modern architecture, trendy city aesthetic',
  jeju_island:    'Jeju Island South Korea, volcanic island, Hallasan mountain, yellow canola fields, dramatic coastal cliffs',
  singapore:      'Gardens by the Bay Singapore, futuristic Supertree Grove glowing at twilight, Marina Bay Sands, tropical waterfront',
  vietnam:        'Ha Long Bay Vietnam, 3000 limestone karst islands rising from UNESCO emerald waters, traditional junk boats',
  maldives:       'Overwater Bungalow Maldives, luxury overwater villa, crystal-clear lagoon, coral reef below, pristine turquoise sea',
  dubai_desert:   'Dubai Desert Dunes UAE, sweeping golden sand dunes at sunset, dramatic red-orange desert landscape',
  abu_dhabi:      'Sheikh Zayed Grand Mosque Abu Dhabi, magnificent white marble mosque, 82 domes, reflective pools, intricate Islamic architecture',
  cappadocia:     'Cappadocia Turkey, hundreds of colorful hot air balloons at sunrise above surreal fairy chimney rock formations',
  paris_eiffel:   'Eiffel Tower Paris France, iconic iron lattice tower from Trocadero plaza, golden Parisian light',
  paris_street:   'Montmartre Paris France, charming cobblestone Parisian streets, Belle Epoque buildings, romantic artistic quarter',
  lake_como:      'Lake Como Lombardy Italy, breathtaking Italian Alpine lake, Villa del Balbianello, cypress trees, dramatic mountains',
  venice:         'Grand Canal Venice Italy, historic gondolas on sun-dappled canal, colorful Renaissance palazzos lining the water',
  santorini:      'Oia Village Santorini Greece, iconic white cubic buildings, blue-domed churches, dramatic caldera cliff, Aegean Sea',
  swiss_alps:     'Swiss Alps Switzerland, majestic snow-capped peaks, pristine alpine meadows with wildflowers, glacier views',
  london_tower:   'Tower Bridge London UK, iconic Victorian Gothic towers, blue steel suspension bridge, River Thames panorama',
  scottish_castle:'Scottish Highland Castle Scotland, medieval stone castle, dramatic Highland landscape, rolling misty hills',
  amalfi:         'Amalfi Coast Campania Italy, dramatic cliffs plunging into Mediterranean turquoise sea, colorful villages',
  tuscany:        "Val d'Orcia Tuscany Italy, rolling Tuscany hills, cypress tree avenues, medieval stone villa, terracotta golden tones",
  neuschwanstein: 'Neuschwanstein Castle Bavaria Germany, fairytale Romanesque Revival castle on rugged cliff, snow-capped Alpine peaks',
  ny_rooftop:     'New York City Rooftop Manhattan USA, iconic Manhattan skyline, skyscrapers, golden sunset over Hudson River',
  central_park:   'Central Park New York City USA, lush green oasis in Manhattan, Bethesda Fountain, tree canopy',
  la_beach:       'Malibu Beach Los Angeles USA, California Pacific coastline, golden sand, crashing waves, warm Pacific sunset',
  california_desert:'Joshua Tree Desert California USA, surreal desert landscape, dramatic Joshua trees, boulder formations, vast open sky',
  las_vegas:      'Las Vegas Chapel Strip USA, iconic neon-lit Las Vegas Strip, glittering casinos and fountains, electric night energy',
  aurora:         'Aurora Borealis Iceland, vivid green and violet aurora curtains dancing across dark arctic sky, frozen lake reflection',
  wd_bali_cliff:  'Uluwatu Cliff Edge Bali, dramatic limestone cliff over Indian Ocean waves, sunset ceremony',
  wd_bali_rice:   'Tegallalang Rice Terrace Ubud Bali, lush terraced rice paddies, tropical garden wedding, natural emerald backdrop',
  wd_beach_white: 'Private White Sand Beach Nusa Dua Bali, pristine white sand, calm turquoise sea, tropical flowers, intimate beach ceremony',
  wd_mountain:    'Mountain Meadow Venue Puncak West Java, misty mountain panorama, cool fresh air, garden ceremony, Java peaks',
  wd_tuscany:     "Tuscan Vineyard Estate Val d'Orcia Italy, rolling Tuscany hills, cypress tree avenues, medieval stone villa",
  wd_ballroom_crystal:'Crystal Ballroom Grand Hyatt Jakarta, opulent crystal chandeliers, white and gold decor, hundreds of candles, floral centerpieces',
  wd_church_gothic:'Jakarta Cathedral, twin Gothic spires, soaring vaulted ceiling, colored stained glass light, ornate wooden pews',
  wd_villa_luxury:'Amankila Royal Villa Bali, heritage colonial luxury villa, frangipani-lined pool terraces, Indian Ocean view',
  wd_pendopo:     'Pendopo Agung Yogyakarta Java, traditional Javanese open-air ceremonial pavilion, carved wooden pillars, batik decorations',
  wd_pura_bali:   'Pura Taman Ayun Mengwi Bali, royal Balinese temple with moat, tiered thatched merus, tropical flowers, sacred atmosphere',
  wd_masjid:      'Istiqlal Grand Mosque Jakarta, Southeast Asia largest mosque, grand marble interior, dramatic arched colonnade',
  en_rooftop:     'Rooftop Lounge Jakarta Skyline, 360-degree Jakarta skyline, golden city lights bokeh, intimate rooftop setup',
  en_cafe:        'Cozy Cafe Menteng Jakarta, warm Edison bulb bokeh, exposed brick walls, wooden furniture, intimate atmosphere',
  en_alley:       'Braga Street Bandung West Java, charming Dutch colonial alley, Art Deco facades, cobblestone street, warm afternoon light',
  en_forest:      'Pine Forest Cikole Bandung, towering pine trees, dappled light rays, mystical forest floor, morning mist',
  en_beach_casual:'Sanur Beach Bali at Low Tide, calm shallow beach, mirror-flat water reflecting golden sky, barefoot lifestyle',
  en_garden:      'Kebun Raya Bogor Botanical Garden, Victorian-era botanical garden, rare tropical plants, glasshouse, specimen trees',
  en_proposal_floral: 'Floral Arch Proposal Setup, archway covered in fresh roses and peonies, rose petals on ground, candles lit',
  en_proposal_candles:'Candlelit Rooftop Proposal Setup, hundreds of flickering candles in heart shape, rose petals, string lights, magical atmosphere',
};

export function resolveLocation(key, customValue) {
  if (!key || key === 'custom') return customValue?.trim() || '';
  if (LOCATION_DATA[key]) return LOCATION_DATA[key];
  return key.trim();
}
